/bin/cp *.py ../scene_graph_benchmark_tl_1/.
/bin/cp *.py ../scene_graph_benchmark_tl_2/.
/bin/cp *.py ../scene_graph_benchmark_tl_3/.
/bin/cp *.py ../scene_graph_benchmark_tl_4/.
/bin/cp *.py ../scene_graph_benchmark_tl_5/.
/bin/cp *.py ../scene_graph_benchmark_tl_6/.
/bin/cp *.py ../scene_graph_benchmark_tl_7/.
/bin/cp *.py ../scene_graph_benchmark_tl_8/.
/bin/cp *.py ../scene_graph_benchmark_tl_9/.
/bin/cp *.py ../scene_graph_benchmark_tl_10/.
/bin/cp *.py ../scene_graph_benchmark_tl_11/.
/bin/cp *.py ../scene_graph_benchmark_tl_12/.
/bin/cp *.py ../scene_graph_benchmark_tl_13/
/bin/cp *.py ../scene_graph_benchmark_tl_14/.
/bin/cp *.py ../scene_graph_benchmark_tl_15/.
/bin/cp *.py ../scene_graph_benchmark_tl_16/.
/bin/cp *.py ../scene_graph_benchmark_tl_17/.
/bin/cp *.py ../scene_graph_benchmark_tl_18/.
/bin/cp *.py ../scene_graph_benchmark_tl_19/.
/bin/cp *.py ../scene_graph_benchmark_tl_20/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_1/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_2/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_3/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_4/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_5/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_6/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_7/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_8/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_9/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_10/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_11/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_12/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_13/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_14/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_15/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_16/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_17/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_18/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_19/.
/bin/cp obj_thred.json ../scene_graph_benchmark_tl_20/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_1/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_2/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_3/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_4/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_5/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_6/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_7/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_8/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_9/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_10/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_11/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_12/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_13/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_14/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_15/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_16/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_17/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_18/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_19/.
/bin/cp allgoogdfea.bin ../scene_graph_benchmark_tl_20/.

/bin/cp tools/*.py ../scene_graph_benchmark_tl_1/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_2/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_3/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_4/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_5/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_6/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_7/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_8/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_9/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_10/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_11/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_12/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_13/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_14/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_15/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_16/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_17/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_18/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_19/tools/.
/bin/cp tools/*.py ../scene_graph_benchmark_tl_20/tools/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_20/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_19/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_18/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_17/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_16/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_15/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_14/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_13/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_12/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_11/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_10/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_9/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_8/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_7/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_6/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_5/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_4/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_3/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_2/tools/mini_tsv/.
/bin/cp tools/mini_tsv/*.py ../scene_graph_benchmark_tl_1/tools/mini_tsv/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_1/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_2/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_3/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_4/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_5/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_6/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_7/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_8/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_9/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_10/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_11/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_12/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_13/.
##/bin/cp imageall.bin ../scene_graph_benchmark_tl_14/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_15/.
#/bin/cp imageall.bin ../scene_graph_benchmark_tl_16/.
